Module6 task2
htmlacademy-php/59949-yeticave-12 pull request #11
Opened 2021-11-07 20:41 UTC by Funky-Juice

2021-11-11 07:09 UTC, tagedo requested changes
Сергей, есть к чему стремиться в плане организации и структурирования кода.
Давай еще sql и js вынесем в отдельные папки.

2021-11-11 07:09 UTC, tagedo commented on add-lot.php
> +$link = mysqli_connect("localhost", "root", "root","yeticave");
данные для подключения выносим в config.php - этот файл добавляем в .gitignore (секретные данные не должны попасть в репозиторий)

2021-11-11 07:09 UTC, tagedo commented on add-lot.php
> +$categoriesList = mysqli_fetch_all($result, MYSQLI_ASSOC);
начиная со строки подключения к БД  - участок кода дублируется на каждой странице (копипаст) - подумай, что можно с этим сделать

2021-11-11 07:09 UTC, tagedo commented on add-lot.php
> +    if (!count($errors)) {
лучше использовать более явный способ проверки - !empty($errors)

2021-11-11 07:09 UTC, tagedo commented on add-lot.php
> +        if (!$rate || !is_numeric($rate)) {
что проверяет !$rate ? - проведи эксперимент
чтобы убедиться, что введенное значение - положительное число, делаем явное приведение к нужному типу и сравниваем с нулем

2021-11-11 07:09 UTC, tagedo commented on add-lot.php
> +        if (!$step || !ctype_digit($step)) {
чтобы убедиться, что введенное значение - положительное число, делаем явное приведение к нужному типу и сравниваем с нулем

2021-11-11 07:09 UTC, tagedo commented on add-lot.php
> +
в целом по валидации - 
1. в учебнике есть рекомендация вынести каждую проверку в отдельную функцию - советую так и поступить - это поможет структурировать код, будет удобнее добавлять новые правила.
2. подумай, какой массив правил можно сделать, чтобы по нему пройти функциями валидации.
3. выносим валидацию в отдельный файл
4. кстати, достаточно ли сейчас правил? на длину строки, например, название лота не нужно проверить?

2021-11-11 07:09 UTC, tagedo commented on helpers.php
> +    if (isset($_FILES[$fieldName])) {
когда возможно, сокращаем количество кода внутри условия - для читабельности, для этого меняем условие на противоположное
ошибки здесь нет, просто имей в виду

2021-11-11 07:09 UTC, tagedo commented on helpers.php
> + */
В файле helpers.php в корне вашего проекта вы можете найти функцию is_date_valid, которая упростит проверку формата даты.
эта функция не подошла?

2021-11-11 07:09 UTC, tagedo commented on lot.php
> +    HAVING l.id";
выражение HAVING имеет смысл после выражения GROUP BY, когда нам нужно наложить условие на уже сагрегированные (сгруппированные) данные
здесь лишнее

2021-11-11 07:09 UTC, tagedo commented on lot.php
> +$sql = "SELECT l.*, c.title AS category_title, (initial_price + IFNULL(SUM(b.amount), 0)) AS current_price FROM lots l
лучше избегать использования *
размерность таблицы (количество столбцов) в будущем может вырасти и в выборку будет попадать лишняя информация

2021-11-12 08:48 UTC, Funky-Juice commented on lot.php
> +    HAVING l.id";
если запрашивать данные по несуществующему id лота, то вместо пустого массива приходит один элемент с null'ами 
![image](https://user-images.githubusercontent.com/16765154/141438031-2495253e-3126-48e6-8c19-e4bbfe704b2b.png)

having как то решает эту проблему

2021-11-12 10:23 UTC, tagedo commented on lot.php
> +    HAVING l.id";
потому что SUM есть, а GROUP BY нет, а ведь именно суммирование по ид лота мы и имеем в виду
давай явно укажем группировку по ид лота и тогда уже этой пустой строки не будет
а то анализатор сразу говорит, что использование HAVING здесь не эффективно

2021-11-19 20:29 UTC, Funky-Juice commented on helpers.php
> + */
увидел уже после написания своего велосипеда.
было жалко потраченных усилий, так что решил оставить свой вариант =)

2021-11-19 21:05 UTC, Funky-Juice commented on helpers.php
> +    if (isset($_FILES[$fieldName])) {
условие поменял, но на количестве кода это не отразилось.
или я неправильно понял

2021-11-20 12:45 UTC, tagedo commented on queries/categories.php
> +function fetch_categories($conn) {
Получение категорий - это **только** получение категорий. Всегда стремимся, чтобы функция делала что-то одно.
То есть на момент получения категорий все вопросы с подключением к БД уже решены, мы точно знаем, что коннект есть и кодировка установлена. Просто получили готовый коннект и пользуемся.

2021-11-20 12:45 UTC, tagedo commented on db-methods.php
> +}
я бы оформила получение коннекта с установкой кодировки в виде функции и в остальном коде ее вызывала
таким образом будет более очевидно, как мы получили переменную $db_conn:
$db_conn = getDbConnect();
а если коннекта не получилось, то спрашиваем почему:
$error = getDbConnectError();
и в основном коде отрисовываем ошибку show_error($error); 
методы по работе с БД рисованием заниматься не должны,

2021-11-20 12:50 UTC, tagedo commented on db-methods.php
> +}
такие обертки над функциями mysqli очень удобны, их делают и для получения одной строки, и для insert, и для update
и получение ошибки - тоже отдельная функция, возвращающая ошибку, а в вызывающем коде - отрисовываем

2021-11-20 12:53 UTC, tagedo commented on queries/lots.php
> +    return fetch_from_db($conn, $sql);
здесь как и с категориями - в аргументе получаем коннект и пользуемся, к БД никаких вопросов не имеем

2021-11-20 13:09 UTC, tagedo commented on queries/create-lot.php
> +}
обработка ошибки - отдельно от создания лота, здесь - только создание
неудача какой то одной операции не всегда должна приводить к остановке всего скрипта - это решение принимается в вызывающем коде

2021-11-20 13:12 UTC, tagedo commented on queries/lot-by-id.php
> +    GROUP BY l.id";
пока оставляем так, потом вернемся к этому запросу

2021-11-20 13:21 UTC, tagedo commented on helpers.php
> + */
усилия не пропадут - это практика :)
но не нужно забывать и о проверяющем итоговый проект - могут не оценить проявление индивидуальности :(
и относительно snake case - в стандарте нет ограничений на стиль именования переменных, но есть традиция
и опять же - могут не оценить проявление индивидуальности :(

2021-11-20 13:30 UTC, tagedo commented on helpers.php
> +    if (isset($_FILES[$fieldName])) {
у тебя код оборнут в if (isset($_FILES[$fieldName])) 
а если поменять на !isset - инвертировать условие - то при этом условии сразу выходим
а дальше код без условия

2021-12-02 15:47 UTC, tagedo approved these changes
ok

2021-12-02 15:51 UTC, merged